name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build app
        run: npm run build

      - name: Run unit tests
        run: npm run test

      - name: Start app for E2E tests
        run: npm run start &
        env:
          NODE_ENV: development

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        env:
          CI: true

      - name: Run Playwright tests
        run: npx playwright test --list

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Wait for Render service
        run: sleep 30

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-2zvj.onrender.com/health